### ISSUE TITLE
docker example (port 8080) not working

### ISSUE THREAD

**Issue by ktamas77** [alash3al/wsify#11]
I was trying to follow the given examples, downloaded & started the docker version, and tried to connect with the recommneded chrome websocket client to `ws://localhost:8080/subscribe` but it failed every time. Please advise.

**Comment by alash3al** [comment]
sorry for the so late reply, but the docker example is working as expected for anyone who used it, could you tell me what is your platform, and what is happening after running the command?

**Comment by azuddin** [comment]
@alash3al i receive `invalid` error:
![image](https://user-images.githubusercontent.com/8788888/159124937-52e928a1-41f8-4501-b9ec-d5647731b50c.png)

here's the command i ran:
![image](https://user-images.githubusercontent.com/8788888/159125061-743f83db-9980-41cd-968d-997c496553c2.png)


and no error shown when i test in websocket client
is my usage above correct?

**Comment by azuddin** [comment]
turns out that `host` only work on linux 😂 
@alash3al i created PR for updated readme https://github.com/alash3al/wsify/pull/18 
now its working fine
