### ISSUE TITLE
how to use webhook?

### ISSUE THREAD

**Issue by shinnlu** [alash3al/wsify#13]
when i run:wsify --events="", everything goes correct
but after i run:wsify, i can't connect to wsify anymore.

**Comment by eislambey** [comment]
when you start `wsify` webhook default is `http://localhost:8000`
if you didnt have proper webhook on localhost:8000 you cant connect.

**Comment by alash3al** [comment]
@shinnlu 

`wsify --events=""` means that you don't need wsify to send an event to your webhook, when removing `--events=""` then, wsify uses the default setting which can be viewed by running `wsify --help`, in that case, as @eislambey mentioned, you must set a proper webhook so wsify can pass/reject connections based on that webhook response.

**Comment by shinnlu** [comment]
thanks for reply, but how could i set webhook to allow/disallow users.
