### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by ghost** [alash3al/wsify#3]
It looks like there is no storage currently ?

Would be nice so that events not delivered do eventually get delivered.
Budget might be a good option as it also has  raft these days

**Comment by alash3al** [comment]
Wsify created to be just a messaging layer over websockets between your backend and the browser, so your backend is responsible for storing the messages and send/resend it when needed.

If I didn't understand you well, just explain more, I'm open to any opinion that will make wsify more powerful.

**Comment by ghost** [comment]
I think you did understand me. That does answer my question.

For me , retry is important and the only way to do that is to have durable state.
I think that its not a big deal to add it though.. 

I was suggesting Badger ( not "Budget" - that was a type sorry).  
This person is using Badger with Raft for his durable PUB sub in golang.
Its got bigger and more complex architecture then yours, and each to hsi own as they say.
But it does shwo the idea of Durable state and a good golang lib for it.

happy to discuss further of course.

**Comment by alash3al** [comment]
For me, if I want to implement a durable push notification "as an example":

- I can get notified on client connect/disconnect/subscribe/unsubscribe
- Based on that I can set the status of each client in my own db
- when I want to push a message to a client, I will get its status
- if the client were disconnected, just queue them,
- else, push them to wsify
- and when the clients connects again, you will get notified, then push the queued messages to him.

> wsify is just a layer pub/sub only like "redis pubsub" but with more features like webhooks, websocket endpoints.

**Comment by ghost** [comment]
good point. That means you get control fully over the process.
I will try it :) if you have any code showing off that feel free to link it....

**Comment by alash3al** [comment]
Yeah, and that is the main key point of `wsify`, but for any more examples, soon I'll show more and writing tutorials for it.

**Comment by ghost** [comment]
Thanks. It makes sense.
I will try to also make a few examples..

**Comment by agborkowski** [comment]
@gedw99 u have many ampq brokers with durability support so i dont get a point to complex "wsify" project ?

**Comment by ghost** [comment]
its about retry. No durability, no retry.
Its a cqrs pattern.

anyway...
