### ISSUE TITLE
gometalinter

### ISSUE THREAD

**Issue by RO-29** [alash3al/wsify#5]
FYI I use gometalinter with following flags in my projects,

(https://github.com/alecthomas/gometalinter)

```
gometalinter --enable-all -D dupl -D lll -D gas -D goconst -D interfacer -D safesql -D test -D testify -D vetshadow\
 --tests --vendor --warn-unmatched-nolint --deadline=10m --concurrency=2 --enable-gc ./...
```

when I ran this on your project I see some issues, do you accept contributions? I can submit the PR

**Comment by alash3al** [comment]
@RO-29 , Sure, You can contribute

**Comment by RO-29** [comment]
https://github.com/alash3al/wsify/pull/6

**Comment by RO-29** [comment]
https://github.com/alash3al/wsify/pull/6 is merged, closing this
