### ISSUE TITLE
Trouble using wsify

### ISSUE THREAD

**Issue by gradha** [alash3al/wsify#7]
Hi, I wanted to try the project but I'm not having much success. I've downloaded the osx 64bit darwin binary and run it without webhooks like `./wsify_darwin_amd64  -events ""`. Now, when I open an instance of [socket-io-tester](https://github.com/AppSaloon/socket.io-tester) and enter the address `http://localhost:4040/subscribe` I get periodic errors in the terminal:

```
{"time":"2018-03-27T18:13:30.993363+02:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"285","message":"code=404, message=Not Found"}
{"time":"2018-03-27T18:13:31.762112+02:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"285","message":"code=404, message=Not Found"}
{"time":"2018-03-27T18:13:34.296958+02:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"285","message":"code=404, message=Not Found"}
```

I guess the errors might be related to the tester app requiring a specific handshake/protocol/whatever, so I changed to a simple script using python. I copied the client example from the [python WebSockets](https://websockets.readthedocs.io/en/stable/) documentation and replaced the typical hello world string with the JSON payload from your readme:

```py
#!/usr/bin/env python3

import asyncio
import websockets

async def hello(uri):
    j = '{"payload": "hi from the terminal", "channel": "testchan"}'
    async with websockets.connect(uri) as websocket:
        await websocket.send(j)

asyncio.get_event_loop().run_until_complete(
    hello('ws://localhost:4040/subscribe'))
```

This time when I run the python script the wsify server crashes with:

```
$ ./wsify_darwin_amd64  -events ""
[*] Welcome to WSIFY 2.0
[*] Listening for connections on address :4040  ...
⇨ http server started on [::]:4040
panic: send on closed channel

goroutine 7 [running]:
main.WSHandler.func3(0xc4200b0640, 0x0, 0x0, 0xc42005a640, 0xc4200202a0)
	/home/alash3al/Dev/go/workspace/src/github.com/alash3al/wsify/server.go:92 +0x3f0
created by main.WSHandler
	/home/alash3al/Dev/go/workspace/src/github.com/alash3al/wsify/server.go:70 +0x2f4
```

Seeing the closed channel thing, maybe the problem is the script not waiting to receive any data. So looking at the [client basic websocket example](https://websockets.readthedocs.io/en/stable/intro.html#basic-example) I modified the test script to include a newline character in the payload and wait to receiving data:

```python
#!/usr/bin/env python3

import asyncio
import websockets

async def hello(uri):
    j = '{"payload": "hi from the terminal", "channel": "testchan"}\n'
    async with websockets.connect(uri) as websocket:
        await websocket.send(j)
        print("Sent payload")
        result = await websocket.recv()
        print("Received answer")

asyncio.get_event_loop().run_until_complete(
    hello('ws://localhost:4040/subscribe'))
```

This version however seems to hang after printing `Sent payload` and the server doesn't seem to reflect any activity. Any pointers on what I'm doing wrong?

**Comment by alash3al** [comment]
Dear @gradha 

Your script connects to the wsify and waits for the first message then exists, there should be a main loop that executes that sub-loop so it won't exists.

Here is an example:

```python
#!/usr/bin/env python

import asyncio
import websockets
import json

async def hello():
    async with websockets.connect('ws://localhost:4040/subscribe') as websocket:
        await websocket.send(json.dumps({"action": "subscribe", "value": "testchan"}))
        while True:
            data = await websocket.recv()
            print("< {}".format(data))

asyncio.get_event_loop().run_until_complete(hello())
```

**Comment by alash3al** [comment]
about the mentioned exception in `wsify` itself, you can use the [latest version](https://github.com/alash3al/wsify/releases/tag/v2.2)

**Comment by gradha** [comment]
None of the examples work for me but I guess the problem is the client. Thanks, I'll keep looking.

**Comment by alash3al** [comment]
No worries bro, the problem is the client, because it listens only for one message, but it should loop, and that is what I did above, I put the `websocket.recv()` in a while loop, so it listens for any incoming message, not just one.

See [this](https://websockets.readthedocs.io/en/stable/intro.html#consumer) as a refrence.
